# 1. Импорт библиотеки NumPy

In [2]:
import numpy as np

# 2. Создание массивов

In [3]:
# Из обычного списка
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print(f"Из списка {list_data}:")
print(f"Массив: {arr_from_list}")

Из списка [1, 2, 3, 4, 5]:
Массив: [1 2 3 4 5]


In [4]:
# Массив из вложенного списка (матрица)
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix_data)
print(f"\nМатрица 3x3:")
print(matrix)


Матрица 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# С использованием zeros, ones, arange
zeros_arr = np.zeros(5)
print(f"\nZeros (5 элементов): {zeros_arr}")


Zeros (5 элементов): [0. 0. 0. 0. 0.]


In [6]:
ones_arr = np.ones((2, 3))  # 2 строки, 3 столбца
print(f"Ones (2x3):\n{ones_arr}")

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arange_arr = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print(f"Arange (0-10, шаг 2): {arange_arr}")

Arange (0-10, шаг 2): [0 2 4 6 8]


In [8]:
linspace_arr = np.linspace(0, 1, 5)  # 5 точек от 0 до 1
print(f"Linspace (0-1, 5 точек): {linspace_arr}")
print()

Linspace (0-1, 5 точек): [0.   0.25 0.5  0.75 1.  ]



# 3. Атрибуты массивов

In [9]:
print(f"Матрица shape: {matrix.shape}")
print(f"Матрица dtype: {matrix.dtype}")
print(f"Матрица размер: {matrix.size}")
print(f"Матрица измерения: {matrix.ndim}D")
print()

Матрица shape: (3, 3)
Матрица dtype: int64
Матрица размер: 9
Матрица измерения: 2D



# 4. Индексирование и срезы

In [10]:
# Одномерный массив
arr_1d = np.array([10, 20, 30, 40, 50])
print(f"Исходный массив: {arr_1d}")
print(f"Первый элемент: {arr_1d[0]}")
print(f"Последний элемент: {arr_1d[-1]}")
print(f"Срез [1:4]: {arr_1d[1:4]}")
print(f"Срез [::2]: {arr_1d[::2]}")  # Каждый второй элемент

Исходный массив: [10 20 30 40 50]
Первый элемент: 10
Последний элемент: 50
Срез [1:4]: [20 30 40]
Срез [::2]: [10 30 50]


In [11]:
# Двумерный массив
print(f"\nМатрица:\n{matrix}")
print(f"Элемент [1,2]: {matrix[1, 2]}")  # Строка 1, столбец 2
print(f"Первая строка: {matrix[0, :]}")
print(f"Последний столбец: {matrix[:, -1]}")
print(f"Подматрица 2x2:\n{matrix[:2, :2]}")
print()


Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [1,2]: 6
Первая строка: [1 2 3]
Последний столбец: [3 6 9]
Подматрица 2x2:
[[1 2]
 [4 5]]



# 5. Векторные операции и статистика

In [12]:
# Векторные операции
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [13]:
print(f"Массив a: {a}")
print(f"Массив b: {b}")
print(f"a + b: {a + b}")
print(f"a * b: {a * b}")
print(f"a * 2: {a * 2}")  # Умножение на скаляр
print(f"a ** 2: {a ** 2}")  # Возведение в квадрат

Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
a + b: [ 6  8 10 12]
a * b: [ 5 12 21 32]
a * 2: [2 4 6 8]
a ** 2: [ 1  4  9 16]


In [14]:
# Статистика
data = np.array([2, 4, 6, 8, 10])
print(f"\nДанные: {data}")
print(f"Среднее: {np.mean(data):.2f}")
print(f"Сумма: {np.sum(data)}")
print(f"Максимум: {np.max(data)}")
print(f"Минимум: {np.min(data)}")
print(f"Стандартное отклонение: {np.std(data):.2f}")
print()


Данные: [ 2  4  6  8 10]
Среднее: 6.00
Сумма: 30
Максимум: 10
Минимум: 2
Стандартное отклонение: 2.83



# Пример 1: Генерация случайных данных и нормализация

In [15]:
print("Пример 1: Генерация и нормализация данных")
random_data = np.random.randint(0, 100, 10)
normalized = (random_data - np.min(random_data)) / (np.max(random_data) - np.min(random_data))
print(f"Случайные данные: {random_data}")
print(f"Нормализованные: {normalized}")
print()

Пример 1: Генерация и нормализация данных
Случайные данные: [ 9  7 90 71 62 28 63 16 46 10]
Нормализованные: [0.02409639 0.         1.         0.77108434 0.6626506  0.25301205
 0.6746988  0.10843373 0.46987952 0.03614458]



# Пример 2: Работа с булевой маской

In [16]:
print("Пример 2: Фильтрация данных")
temperatures = np.array([15, 20, 25, 18, 30, 22])
hot_days = temperatures[temperatures > 22]
print(f"Температуры: {temperatures}")
print(f"Жаркие дни (>22°C): {hot_days}")
print()

Пример 2: Фильтрация данных
Температуры: [15 20 25 18 30 22]
Жаркие дни (>22°C): [25 30]



# Пример 3: Матричные операции

In [17]:
print("Пример 3: Матричные операции")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(A, B)
print(f"Матрица A:\n{A}")
print(f"Матрица B:\n{B}")
print(f"Произведение A×B:\n{matrix_product}")

Пример 3: Матричные операции
Матрица A:
[[1 2]
 [3 4]]
Матрица B:
[[5 6]
 [7 8]]
Произведение A×B:
[[19 22]
 [43 50]]
